Repository gdsc-konkuk/Plantory-Server, pull requests merged in 2024-02, with the labels that each got.

#53 feat(data.sql): 더미데이터 소량 추가
  src/main/resources/application.yml
  src/main/resources/sql/data.sql
Labels: ⚙️ 인프라 ⚙️

#54 version 1.0.1
  src/main/resources/application.yml
  src/main/resources/sql/data.sql
Labels: ⚙️ 인프라 ⚙️

#58 [Feat] date region change to seoul #57
  src/main/kotlin/gdsc/plantory/PlantoryApplication.kt
  src/main/kotlin/gdsc/plantory/event/notification/WaterCycleEventListener.kt
  src/main/kotlin/gdsc/plantory/plant/service/ReminderService.kt
Labels: 🚀 기능 구현 🚀

#61 feat(TempApi): 알림 테스트 전송용 API 구현
  src/main/kotlin/gdsc/plantory/plant/presentation/TempApi.kt
  src/main/kotlin/gdsc/plantory/plant/presentation/dto/AlarmRequest.kt
Labels: 🚀 기능 구현 🚀

#63 [Fix] Local Image Store
  src/main/kotlin/gdsc/plantory/common/config/WebMvcConfiguration.kt
  src/main/kotlin/gdsc/plantory/common/support/photo/PhotoLocalManager.kt
  src/main/kotlin/gdsc/plantory/plant/presentation/dto/CompanionPlantCreateRequest.kt
  src/main/kotlin/gdsc/plantory/plant/service/PlantService.kt
  src/main/resources/application.yml
  src/test/resources/application.yml
Labels: 🚨 심각한 버그 🚨
