Repository gdsc-konkuk/Plantory-Server, pull requests merged in 2024-01, with the labels that each got.

#12 [Feat] plant register
  build.gradle.kts
  src/main/kotlin/gdsc/plantory/common/support/photo/PhotoLocalManager.kt
  src/main/kotlin/gdsc/plantory/common/support/photo/PhotoNameGenerator.kt
  src/main/kotlin/gdsc/plantory/member/domain/Member.kt
  src/main/kotlin/gdsc/plantory/plant/domain/CompanionPlantRepository.kt
  src/main/kotlin/gdsc/plantory/plant/presentation/PlantCommandApi.kt
  src/main/kotlin/gdsc/plantory/plant/presentation/dto/CompanionPlantCreateRequest.kt
  src/main/kotlin/gdsc/plantory/plant/service/PlantService.kt
  src/main/kotlin/gdsc/plantory/plantInformation/domain/PlantInformation.kt
  src/main/kotlin/gdsc/plantory/plantInformation/domain/PlantInformationRepository.kt
  src/main/kotlin/gdsc/plantory/plantInformation/domain/WaterCycle.kt
  src/main/resources/application.yml
  src/test/kotlin/gdsc/plantory/acceptance/CompanionPlantAcceptanceTest.kt
  src/test/kotlin/gdsc/plantory/acceptance/CompanionPlantStep.kt
  src/test/kotlin/gdsc/plantory/common/support/photo/PhotoLocalManagerTest.kt
  src/test/kotlin/gdsc/plantory/common/support/photo/PhotoNameGeneratorTest.kt
  src/test/kotlin/gdsc/plantory/fixture/CompanionPlantFixture.kt
  src/test/kotlin/gdsc/plantory/fixture/FileFixture.kt
  src/test/kotlin/gdsc/plantory/util/DatabaseLoader.kt
  src/test/kotlin/gdsc/plantory/util/ImageCleaner.kt
  src/test/kotlin/gdsc/plantory/util/ImageCleanerExtension.kt
  src/test/resources/application.yml
Labels: 🚀 기능 구현 🚀

#14 [Feat] lookup plants
  src/main/kotlin/gdsc/plantory/plant/domain/CompanionPlant.kt
  src/main/kotlin/gdsc/plantory/plant/domain/CompanionPlantRepository.kt
  src/main/kotlin/gdsc/plantory/plant/presentation/PlantCommandApi.kt
  src/main/kotlin/gdsc/plantory/plant/presentation/PlantQueryApi.kt
  src/main/kotlin/gdsc/plantory/plant/presentation/dto/CompanionPlantCreateRequest.kt
  src/main/kotlin/gdsc/plantory/plant/presentation/dto/CompanionPlantResponse.kt
  src/main/kotlin/gdsc/plantory/plant/service/PlantService.kt
  src/test/kotlin/gdsc/plantory/acceptance/CompanionPlantAcceptanceTest.kt
  src/test/kotlin/gdsc/plantory/acceptance/CompanionPlantStep.kt
  src/test/kotlin/gdsc/plantory/member/domain/MemberTest.kt
  src/test/kotlin/gdsc/plantory/plantInformation/domain/PlantInformationTest.kt
Labels: 🚀 기능 구현 🚀

#18 [Feat] plant history
  build.gradle.kts
  src/main/kotlin/gdsc/plantory/common/exception/dto/ErrorDtos.kt
  src/main/kotlin/gdsc/plantory/plant/domain/CompanionPlant.kt
  src/main/kotlin/gdsc/plantory/plant/domain/CompanionPlantRepository.kt
  src/main/kotlin/gdsc/plantory/plant/domain/History.kt
  src/main/kotlin/gdsc/plantory/plant/domain/HistoryType.kt
  src/main/kotlin/gdsc/plantory/plant/domain/PlantRecord.kt
  src/main/kotlin/gdsc/plantory/plant/presentation/PlantCommandApi.kt
  src/main/kotlin/gdsc/plantory/plant/presentation/PlantQueryApi.kt
  src/main/kotlin/gdsc/plantory/plant/presentation/dto/CompanionPlantDto.kt
  src/main/kotlin/gdsc/plantory/plant/presentation/dto/CompanionPlantHistoryRequest.kt
  src/main/kotlin/gdsc/plantory/plant/presentation/dto/CompanionPlantsLookupResponse.kt
  src/main/kotlin/gdsc/plantory/plant/service/PlantService.kt
  src/main/kotlin/gdsc/plantory/plantInformation/domain/PlantInformation.kt
  src/test/kotlin/gdsc/plantory/acceptance/CompanionPlantAcceptanceTest.kt
  src/test/kotlin/gdsc/plantory/acceptance/CompanionPlantStep.kt
  src/test/kotlin/gdsc/plantory/acceptance/MemberAcceptanceTest.kt
  src/test/kotlin/gdsc/plantory/fixture/CompanionPlantFixture.kt
  src/test/kotlin/gdsc/plantory/plant/domain/CompanionPlantTest.kt
  src/test/kotlin/gdsc/plantory/plant/domain/HistoryTypeTest.kt
  src/test/kotlin/gdsc/plantory/util/DatabaseLoader.kt
Labels: 🚀 기능 구현 🚀

#17 [Feat] plant_records 등록 및 조회 API
  src/main/kotlin/gdsc/plantory/common/domain/BaseTimeEntity.kt
  src/main/kotlin/gdsc/plantory/common/exception/CommonExceptionHandler.kt
  src/main/kotlin/gdsc/plantory/common/support/AccessDeviceToken.kt
  src/main/kotlin/gdsc/plantory/member/dto/MemberDtos.kt
  src/main/kotlin/gdsc/plantory/member/presentation/MemberCommandApi.kt
  src/main/kotlin/gdsc/plantory/member/presentation/dto/MemberCreateRequest.kt
  src/main/kotlin/gdsc/plantory/plant/domain/Comment.kt
  src/main/kotlin/gdsc/plantory/plant/domain/CompanionPlant.kt
  src/main/kotlin/gdsc/plantory/plant/domain/CompanionPlantRepository.kt
  src/main/kotlin/gdsc/plantory/plant/domain/ImageUrl.kt
  src/main/kotlin/gdsc/plantory/plant/domain/PlantRecord.kt
  src/main/kotlin/gdsc/plantory/plant/domain/PlantRecords.kt
  src/main/kotlin/gdsc/plantory/plant/presentation/PlantCommandApi.kt
  src/main/kotlin/gdsc/plantory/plant/presentation/PlantQueryApi.kt
  src/main/kotlin/gdsc/plantory/plant/presentation/dto/CompanionPlantResponse.kt
  src/main/kotlin/gdsc/plantory/plant/presentation/dto/PlantRecordCreateRequest.kt
  src/main/kotlin/gdsc/plantory/plant/presentation/dto/PlantRecordDto.kt
  src/main/kotlin/gdsc/plantory/plant/presentation/dto/PlantRecordLookupRequest.kt
  src/main/kotlin/gdsc/plantory/plant/service/PlantService.kt
  src/test/kotlin/gdsc/plantory/PlantoryApplicationTests.kt
  src/test/kotlin/gdsc/plantory/acceptance/CommonStep.kt
  src/test/kotlin/gdsc/plantory/acceptance/CompanionPlantAcceptanceTest.kt
  src/test/kotlin/gdsc/plantory/acceptance/CompanionPlantStep.kt
  src/test/kotlin/gdsc/plantory/acceptance/MemberAcceptanceTest.kt
  src/test/kotlin/gdsc/plantory/acceptance/MemberStep.kt
  src/test/kotlin/gdsc/plantory/common/support/DeviceHeaderExtractorTest.kt
  src/test/kotlin/gdsc/plantory/common/support/photo/PhotoLocalManagerTest.kt
  src/test/kotlin/gdsc/plantory/common/support/photo/PhotoNameGeneratorTest.kt
  src/test/kotlin/gdsc/plantory/fixture/CompanionPlantFixture.kt
  src/test/kotlin/gdsc/plantory/fixture/FileFixture.kt
  src/test/kotlin/gdsc/plantory/member/domain/MemberTest.kt
  src/test/kotlin/gdsc/plantory/plant/domain/CompanionPlantTest.kt
  src/test/kotlin/gdsc/plantory/plant/domain/HistoryTest.kt
  src/test/kotlin/gdsc/plantory/plant/domain/HistoryTypeTest.kt
  src/test/kotlin/gdsc/plantory/plant/domain/PlantRecordTest.kt
  src/test/kotlin/gdsc/plantory/plantInformation/domain/PlantInformationTest.kt
  src/test/kotlin/gdsc/plantory/util/DatabaseLoader.kt
Labels: 🚀 기능 구현 🚀

#20 [Feat] plant history 조회 API
  src/main/kotlin/gdsc/plantory/plant/domain/CompanionPlant.kt
  src/main/kotlin/gdsc/plantory/plant/domain/CompanionPlantRepository.kt
  src/main/kotlin/gdsc/plantory/plant/domain/PlantHistories.kt
  src/main/kotlin/gdsc/plantory/plant/domain/PlantHistory.kt
  src/main/kotlin/gdsc/plantory/plant/domain/PlantRecord.kt
  src/main/kotlin/gdsc/plantory/plant/domain/PlantRecords.kt
  src/main/kotlin/gdsc/plantory/plant/presentation/PlantCommandApi.kt
  src/main/kotlin/gdsc/plantory/plant/presentation/PlantQueryApi.kt
  src/main/kotlin/gdsc/plantory/plant/presentation/dto/CompanionPlantsLookupResponse.kt
  src/main/kotlin/gdsc/plantory/plant/presentation/dto/PlantHistoriesLookupRequest.kt
  src/main/kotlin/gdsc/plantory/plant/presentation/dto/PlantHistoriesLookupResponse.kt
  src/main/kotlin/gdsc/plantory/plant/presentation/dto/PlantHistoryDto.kt
  src/main/kotlin/gdsc/plantory/plant/presentation/dto/PlantHistoryRequest.kt
  src/main/kotlin/gdsc/plantory/plant/service/PlantService.kt
  src/test/kotlin/gdsc/plantory/acceptance/CompanionPlantAcceptanceTest.kt
  src/test/kotlin/gdsc/plantory/acceptance/CompanionPlantStep.kt
  src/test/kotlin/gdsc/plantory/fixture/CompanionPlantFixture.kt
  src/test/kotlin/gdsc/plantory/fixture/MemberFixture.kt
  src/test/kotlin/gdsc/plantory/fixture/PlantInformationFixture.kt
  src/test/kotlin/gdsc/plantory/plant/domain/PlantHistoryTest.kt
  src/test/kotlin/gdsc/plantory/util/DatabaseLoader.kt
Labels: 🚀 기능 구현 🚀

#24 [Feat] palnt 삭제 API
  src/main/kotlin/gdsc/plantory/plant/domain/CompanionPlantRepository.kt
  src/main/kotlin/gdsc/plantory/plant/presentation/PlantCommandApi.kt
  src/main/kotlin/gdsc/plantory/plant/presentation/dto/CompanionPlantDeleteRequest.kt
  src/main/kotlin/gdsc/plantory/plant/service/PlantService.kt
  src/test/kotlin/gdsc/plantory/acceptance/CompanionPlantAcceptanceTest.kt
  src/test/kotlin/gdsc/plantory/acceptance/CompanionPlantStep.kt
Labels: 🚀 기능 구현 🚀

#40 [Feat] Add record field #38
  src/main/kotlin/gdsc/plantory/plant/domain/CompanionPlant.kt
  src/main/kotlin/gdsc/plantory/plant/domain/CompanionPlantRepository.kt
  src/main/kotlin/gdsc/plantory/plant/presentation/PlantQueryApi.kt
  src/main/kotlin/gdsc/plantory/plant/presentation/dto/CompanionPlantDto.kt
  src/main/kotlin/gdsc/plantory/plant/presentation/dto/CompanionPlantLookupDto.kt
  src/main/kotlin/gdsc/plantory/plant/presentation/dto/CompanionPlantsLookupResponse.kt
  src/main/kotlin/gdsc/plantory/plant/presentation/dto/PlantRecordDto.kt
  src/main/kotlin/gdsc/plantory/plant/presentation/dto/PlantRecordLookupResponse.kt
  src/main/kotlin/gdsc/plantory/plant/service/PlantService.kt
  src/test/kotlin/gdsc/plantory/acceptance/CompanionPlantStep.kt
  src/test/kotlin/gdsc/plantory/plant/service/PlantServiceTest.kt
Labels: 🚀 기능 구현 🚀

#41 [Feat] Swagger 적용
  build.gradle.kts
  src/main/kotlin/gdsc/plantory/common/config/SwaggerConfig.kt
  src/main/kotlin/gdsc/plantory/common/support/AccessDeviceToken.kt
  src/main/kotlin/gdsc/plantory/common/support/DeviceHeaderExtractor.kt
  src/main/kotlin/gdsc/plantory/member/presentation/MemberCommandApi.kt
  src/main/kotlin/gdsc/plantory/plant/presentation/PlantCommandApi.kt
  src/main/kotlin/gdsc/plantory/plant/presentation/PlantQueryApi.kt
  src/main/kotlin/gdsc/plantory/plant/presentation/dto/CompanionPlantCreateRequest.kt
  src/main/kotlin/gdsc/plantory/plant/presentation/dto/CompanionPlantDeleteRequest.kt
  src/main/kotlin/gdsc/plantory/plant/presentation/dto/CompanionPlantDto.kt
  src/main/kotlin/gdsc/plantory/plant/presentation/dto/PlantHistoriesLookupRequest.kt
  src/main/kotlin/gdsc/plantory/plant/presentation/dto/PlantHistoryRequest.kt
  src/main/kotlin/gdsc/plantory/plant/presentation/dto/PlantRecordCreateRequest.kt
  src/main/kotlin/gdsc/plantory/plant/presentation/dto/PlantRecordLookupRequest.kt
  src/main/kotlin/gdsc/plantory/plant/service/PlantService.kt
  src/test/kotlin/gdsc/plantory/acceptance/CompanionPlantAcceptanceTest.kt
  src/test/kotlin/gdsc/plantory/acceptance/CompanionPlantStep.kt
  src/test/kotlin/gdsc/plantory/fixture/CompanionPlantFixture.kt
  src/test/kotlin/gdsc/plantory/plant/service/PlantServiceTest.kt
Labels: 📖 문서화 📖

#42 [Feat] `RECORDING` hsitory 직접 추가 방지
  src/main/kotlin/gdsc/plantory/plant/domain/CompanionPlant.kt
  src/main/kotlin/gdsc/plantory/plant/service/PlantService.kt
  src/test/kotlin/gdsc/plantory/plant/domain/CompanionPlantTest.kt
  src/test/kotlin/gdsc/plantory/plant/service/PlantServiceTest.kt
  src/test/kotlin/gdsc/plantory/util/DatabaseLoader.kt
Labels: 🚀 기능 구현 🚀

#44 [Feat] 식물 정보 조회 API
  src/main/kotlin/gdsc/plantory/plant/presentation/PlantCommandApi.kt
  src/main/kotlin/gdsc/plantory/plant/presentation/PlantQueryApi.kt
  src/main/kotlin/gdsc/plantory/plantInformation/domain/PlantInformationRepository.kt
  src/main/kotlin/gdsc/plantory/plantInformation/presentation/PlantInformationQueryApi.kt
  src/main/kotlin/gdsc/plantory/plantInformation/presentation/dto/PlantInformationDto.kt
  src/main/kotlin/gdsc/plantory/plantInformation/presentation/dto/PlantInformationsLookupResponse.kt
  src/main/kotlin/gdsc/plantory/plantInformation/service/PlantInformationService.kt
  src/test/kotlin/gdsc/plantory/acceptance/PlantInformationAcceptanceTest.kt
  src/test/kotlin/gdsc/plantory/acceptance/PlantInformationStep.kt
Labels: 🚀 기능 구현 🚀

#45 [Infra] 배포
  .github/workflows/Continuous Delivery.yml
  .github/workflows/Deploy.yml
  Dockerfile
  src/main/resources/application.yml
Labels: ⚙️ 인프라 ⚙️

#47 [Fix] CD 워크플로 & 탬플릿 미세 조정
  .github/ISSUE_TEMPLATE/1-FEAT.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/Continuous Delivery.yml
  .github/workflows/Continuous Integration.yml
  .github/workflows/Deploy.yml
Labels: ⚙️ 인프라 ⚙️

#48 [Fix] CD 워크플로 & 탬플릿 미세 조정 (#47)
  .github/ISSUE_TEMPLATE/1-FEAT.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/Continuous Delivery.yml
  .github/workflows/Continuous Integration.yml
  .github/workflows/Deploy.yml
Labels: ⚙️ 인프라 ⚙️

#49 [Refactor] 테스트 Fixture 및 상수 정리
  src/main/kotlin/gdsc/plantory/plant/presentation/dto/PlantHistoryDto.kt
  src/test/kotlin/gdsc/plantory/acceptance/CompanionPlantAcceptanceTest.kt
  src/test/kotlin/gdsc/plantory/fixture/CompanionPlantFixture.kt
  src/test/kotlin/gdsc/plantory/fixture/MemberFixture.kt
  src/test/kotlin/gdsc/plantory/fixture/PlantInformationFixture.kt
  src/test/kotlin/gdsc/plantory/plant/domain/CompanionPlantRepositoryTest.kt
  src/test/kotlin/gdsc/plantory/plant/domain/CompanionPlantTest.kt
  src/test/kotlin/gdsc/plantory/plant/service/PlantServiceTest.kt
  src/test/kotlin/gdsc/plantory/plantInformation/domain/PlantInformationTest.kt
  src/test/kotlin/gdsc/plantory/util/DatabaseLoader.kt
Labels: 🔭 테스트 🔭
